# Generated by Django 4.1.1 on 2022-11-22 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='visitors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
