# Generated by Django 4.1.1 on 2022-11-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0003_remove_landmark_visitors_landmark_visitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='visitors',
        ),
    ]
