# Generated by Django 4.1.1 on 2022-11-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0004_remove_landmark_visitors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmark',
            old_name='photo',
            new_name='main_photo',
        ),
    ]
