# Generated by Django 4.1.1 on 2022-12-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0005_rename_photo_landmark_main_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='rating',
        ),
    ]
