# Generated by Django 4.1.1 on 2022-12-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0006_remove_landmark_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='date_time_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
