# Generated by Django 4.1.1 on 2022-11-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Hello')),
                ('date_time_of_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
