# Generated by Django 4.1.1 on 2022-11-06 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='photos.photo'),
        ),
    ]
