# Generated by Django 4.1.1 on 2022-12-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_tag_landmark_alter_tag_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
