# Generated by Django 4.1.1 on 2022-12-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_remove_notification_receiver_notification_receiver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
