# Generated by Django 4.1.1 on 2022-12-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_notification_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
    ]
