# Generated by Django 4.1.1 on 2022-12-14 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0019_remove_notification_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ManyToManyField(related_name='sent_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
