# Generated by Django 4.1.1 on 2022-11-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripshareuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
