# Generated by Django 4.1.1 on 2022-11-22 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0004_remove_landmark_visitors'),
        ('accounts', '0002_alter_tripshareuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripshareuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='tripshareuser',
            name='landmarks',
            field=models.ManyToManyField(to='landmarks.landmark'),
        ),
    ]
