# Generated by Django 4.1.1 on 2022-12-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0005_rename_photo_landmark_main_photo'),
        ('accounts', '0005_alter_tripshareuser_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripshareuser',
            name='visits',
            field=models.ManyToManyField(blank=True, null=True, related_name='visited_by', to='landmarks.landmark'),
        ),
    ]
