# Generated by Django 4.1.1 on 2022-12-02 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0005_rename_photo_landmark_main_photo'),
        ('accounts', '0006_tripshareuser_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripshareuser',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tripshareuser',
            name='visits',
            field=models.ManyToManyField(related_name='visited_by', to='landmarks.landmark'),
        ),
    ]
