# Generated by Django 4.1.1 on 2022-12-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0005_rename_photo_landmark_main_photo'),
        ('accounts', '0007_alter_tripshareuser_follows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripshareuser',
            name='landmarks',
            field=models.ManyToManyField(blank=True, null=True, to='landmarks.landmark'),
        ),
    ]
