# Generated by Django 4.1.1 on 2022-12-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_tripshareuser_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripshareuser',
            name='landmarks',
        ),
    ]
