# Generated by Django 4.1.1 on 2022-12-07 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_tripshareuser_landmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripshareuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(119)]),
        ),
    ]
