# Generated by Django 4.1.1 on 2022-12-11 22:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripshareuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
