# Generated by Django 4.1.1 on 2022-11-06 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('date_of_publication', models.DateField(auto_now=True)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.comment')),
            ],
        ),
    ]
