# Generated by Django 4.1.1 on 2022-11-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('photos', '0003_remove_photo_comments_photo_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='comments',
        ),
        migrations.AddField(
            model_name='photo',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='common.comment'),
        ),
    ]
