# Generated by Django 4.1.1 on 2022-11-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_remove_photo_comments_photo_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='date_of_publication',
        ),
        migrations.AddField(
            model_name='photo',
            name='date_time_of_publication',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
