# Generated by Django 4.1.1 on 2022-11-25 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0005_rename_photo_landmark_main_photo'),
        ('photos', '0009_photo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='landmark',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='landmarks.landmark'),
        ),
    ]
